name: UpdateDiscordClassNames

on:
#   schedule:
#     - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: VÃ©rification de mise Ã  jour des noms de classe Discord
        uses: fedeericodl/discord-update-classnames@main
        with:
          files: "*.css"
          ignores: "BetterCssEditor.css,NiftyFontPlay.css,RefreshTitleBar.css"
          ignore-class-names: |
            visual-refresh
            app-mount
            user-profile-sidebar
            user-profile-modal
            BetterDiscord
            Powercord
            Replugged
            Aliucord
            Vencord
            bd-
            rp-
            ac-
            vc-
#           report-outdated: true
          target-branch: "updates"
          commit-message: "ðŸ”„ Mise Ã  jour des classes Discord"
          pr-title: "ðŸ”„ Mise Ã  jour des classes Discord Ã  vÃ©rifier"
